### ISSUE TITLE
Some questions about the directory

### ISSUE THREAD

**Issue by GalAster** [b3m2a1/mathematica-BTools#1]
First can't use `Get` to import the created package.

Because `"%\\AppData\\Roaming\\Mathematica\\Paclets\\Applications"` doesn't in the `$Path`.

---

Second, what else should I do after I create a package named "mytest.m" in `"\\Package"`. 

I tried ``<<mytest` `` but `Get` can't find the path.

---

Moreover, buttons in `Docs` run but nothing was generated in `"\\Documentation"`.

`GenerateSymbolPages@fun` works fine but``GenerateDocumentation@"DocGen`" `` only return a empty notebook says

> There are no symbols in the DocGen context.

Maybe I missing some settings.

**Comment by GalAster** [comment]
Thank you. I think I found the problem.

I new a `"myTest.nb"` under "\\Package" and it generate a `"myTest.m"`  like this.

```Mathematica
(* ::Package:: *)
(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(************************************************************************)
myTestfun::ussage="For test";

Begin["`Private`"];
myTestfun:=Echo["1 Succeed!","Test: "];
End[];
```

It works fine.

---

But I have a old project, it made by packages.

For example a file name "myOld.m", then

```Mathematica
BeginPackage["myOld`"];
myOldFun::usage = "sth.";

Begin["`Private`"];
myOldFun=sth...
End[]

EndPackage[]
```

Any idea for me to translate to your framework?

Or I must completely refactored my project?

In fact I don't like programing in `.nb`, I'm using Intelij Idea.

**Comment by GalAster** [comment]
Sometimes when I save the `.nb` the following part would missing.

```Mathematica
(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(************************************************************************)
```

If this missing, the package can't be recognized anymore.

I can't debug this.

---

And I solved previous problem.

```Mathematica
PackageTransfer[nameRaw_]:=
Module[{nameTar,namePakage,fileTar,newPackage,allCell,fileRaw},
    nameTar=StringTake[nameRaw,1;;-3]<>"nb";
    namePakage=FileBaseName[nameRaw];
    fileTar=If[FindFile[nameTar]=!=$Failed,
        NotebookOpen[nameTar,Visible->False],
        newPackage=BTools`Private`Hidden`GenerateNewPackage[];
        NotebookSave[newPackage,nameTar];
        NotebookClose[newPackage];
        Return@PackageTransfer[nameRaw];
    ];
    allCell=NotebookGet[fileRaw=NotebookOpen[nameRaw,Visible->True]][[1,1]];
    SelectionMove[fileTar,Next,CellGroup];
    NotebookWrite[fileTar,allCell];
    NotebookPut[NotebookGet[fileTar]/.{
        RowBox[{RowBox[{"BeginPackage",box___}],";"}]:>Nothing,
        RowBox[{"BeginPackage",box___}]:>Nothing,
        RowBox[{RowBox[{"EndPackage",box___}],";"}]:>Nothing,
        RowBox[{"EndPackage",box___}]:>Nothing,
        RowBox[{"Begin","[","\"`Private`\"","]"}]:>RowBox[{"Begin","[","\"`"<>namePakage<>"`\"","]"}]
    },fileTar];
    NotebookSave[fileTar];
    Echo[namePakage,"Transform Succeed: "];
    NotebookClose[fileTar];
    NotebookClose[fileRaw];
    namePakage
]
```

Now, I can programing in `.wl` and automatic transfer to your framework.

```Mathematica
Packages$Paths = DirectoryName[NotebookFileName[]];
PackageTransfer /@ FileNames["*.wl", Packages$Paths]
```

**Comment by b3m2a1** [comment]
Ohhh. You're talking about my package loading system.

Sorry about the delay on this. 

The issue there is in how I pre-process packages. It generates an automatic loader file which aborts when it hits a `Begin` or `BeginPackage`. , so if you look at all of my packages they look like

```
declaredSym1::usage="dec 1";
declaredSym2::usage="dec 2";

Begin["`Private`"];

imp

End[];
```

Then the `declaredSym1` and `declaredSym2` get configured to autoload at run-time, but nothing below the `Begin` does.

You can still program in .m or .wl files. Either is fine. To get sub-contexts into your package simply add a folder. 

I.e. the structure:

```
MyPkg /
 - MyPkgLoader.wl
 Packages / 
  - myPkg1.m
  Cont1 /
    - myPkg2.m
```

will load the symbols in `myPkg1` into the ``"MyPkg`"`` context, but it will put the symbols from `myPkg2` into ``"MyPkg`Cont1`"``. 

All symbols get auto-loaded in `MyPkgLoader.wl`, so if I want to use `Needs` on a specific package, I set up a .m file in the top-directory that looks like:

```
BeginPackage[
  FileBaseName[DirectoryName@$InputFileName]<>"`"<>
  FileBaseName[$InputFileName]<>"`",
  FileBaseName[DirectoryName@$InputFileName]<>"`"
  ];
EndPackage[]
```
And then just name it, e.g. `Cont1.m`

Thus to have a package where you could load ``"Cont1`"`` via `Needs` you'd set it up like:

```
MyPkg /
 - MyPkgLoader.wl
 - Cont1.m
 Packages / 
  - myPkg1.m
  Cont1 /
    - myPkg2.m
```

and 

``Needs["MyPkg`Cont1`"]``

will then work.

Hope that helps.

**Comment by GalAster** [comment]
Fine, no problem about the file structure now.

Thank you again and...

Again,  `"%\\AppData\\Roaming\\Mathematica\\Paclets\\Applications"` must be added into `$Path` on Win.
