### ISSUE TITLE
How to declare an external package?

### ISSUE THREAD

**Issue by GalAster** [b3m2a1/mathematica-BTools#10]
This is the case in the ordinary case:

```Mathematica
BeginPackage["xxx`",{"JLink`"}]
Begin["`xxx`"]

JavaNew["..."]

End[]
EndPackage[]
```

Now with the `Loader.m`, no longer needed write `BeginPackage`.

But also can't specify `Contexts`, so I must write:

```Mathematica
Begin["`xxx`"]

JLink`JavaNew["..."]

End[]
```

Is there any way to add `JLink` to all sub-packages?

**Comment by b3m2a1** [comment]
You can avoid the `Begin` statements by using a subfolder for subcontexts. This is how BTools manages its context names. The folder name will automatically be used as the context name and all the symbols declared publicly in it will still be exposed to the rest of the package. You can add other contexts to the context path used by the package via the function `PackageExtendContextPath` which you can see in use here: https://github.com/b3m2a1/mathematica-PublicPacletServer/blob/master/Packages/Main.m

**Comment by GalAster** [comment]
cool

**Comment by GalAster** [comment]
I can't understand this: https://github.com/b3m2a1/mathematica-BTools/issues/10#issuecomment-419332475

```Mathematica
fun11::usage="doc11"
fun12::usage="doc12"
fun21::usage="doc2"

Begin[`subpkg1`]
fun11="do something"
fun12="do something"
End[]
Begin[`subpkg2`]
fun21="do something"
End[]
```

Which equal to

```yaml
- Packages\
    - subpkg1\
        - fun11.m
        - fun12.m
    - subpkg2\fun21.m
    - main.m
```

Now in `main.m`

```Mathematica
fun11::usage="doc11"
fun12::usage="doc12"
fun21::usage="doc2"
```

Now nothing will happen when I call `fun11`.

What else should I do, if I call `fun11` and only load `fun11.m`

I mean `fun12.m` and `fun21.m` still lazy load until be called.

Is this possible?

**Comment by b3m2a1** [comment]
@GalAster I think the issue you're hitting is that you actually want to declare `fun11::usage="doc11"` in `fun11.m`. The autoloader finds *all* symbols declared before a `Begin` block in every package file it can and puts all the contexts it builds onto a special context path that's used whenever a file is loaded. This way every symbol knows about every other symbol, but they can be declared in the same place they're defined.

A good example for this is what I do in [this subcontext of BTools](https://github.com/b3m2a1/mathematica-BTools/tree/master/Packages/Paclets). Each file in that directory inherits the ``"BTools`Paclets`"`` context, but each symbol is declared only in the package it's defined in (although this package will not load until the symbol is used). If you drill deeper into the directory structure a similar thing occurs there. E.g. all the symbols declared before the `Begin` [here](https://github.com/b3m2a1/mathematica-BTools/blob/master/Packages/Paclets/DocGen/DocGenCore.m) have the context ``"BTools`Paclets`DocGen`"`` but they're still visible to the rest of the package.
