### ISSUE TITLE
What is the Config folder?

### ISSUE THREAD

**Issue by GalAster** [b3m2a1/mathematica-BTools#14]
1. Is the config folder defined by yourself, can I extend the definition inside?

2. What do the files inside mean?

3. Is it possible to provide something like `$PackageConfig`, which can be used to conveniently store persistent data?

```Mathematica
$PackageConfig["RemovePath", Bundle] = XXX
```

May works like `InitializationValue` and `PersistentValue`

**Comment by b3m2a1** [comment]
@GalAster the Config folder is where I store various files I've found useful in controlling application processing. The files I currently have for it are:

- LoadInfo.wl (or .m): specifies parameters for loading the paclet, in particular things like the loading mode of the package. This is the only file that's used by my autogenerated paclet loader stuff.
- BundleInfo.wl (or .m): specifies parameters for when the paclet gets packed up. My PacletTools stuff is primarily responsible for this

I had two other files in the config for docs and paclet upload, but I find I never have a use for them.

I could add some persistent hook in to all this through some `$PackageConfig` thing, sure, but that will have to wait until I have time to handle a number of other things here and there.
