### ISSUE TITLE
Some questions about the documentation

### ISSUE THREAD

**Issue by GalAster** [b3m2a1/mathematica-BTools#2]
Now let's talk about the documentations generation.

First I load my application.

Then run some functions to activate all packages

At last, using `GenerateDocumentation` to generate the documentations.

---

I find that in `"%AppData%\Roaming\Mathematica\ApplicationData\DocGen\DocPaclets"`.

Everything works good, but when I copy them to  `"myPackage\Documentation"`, all links are broken.

And all the documentations can't be found by searching or `F1`.

**Comment by GalAster** [comment]
And how can I modify the Documentations?

I find the `Template` in `Docs`.

But that's extremely slow, need several minutes to open and very long time to generate.

And that didn't clear the input and output numbering.

The workbench will renumbering from 1

**Comment by b3m2a1** [comment]
@GalAster look at the `DocGen.m` package and its implementation packages in the `_DocGen` folder. The `Template` button loads all the symbols in a given context, so it'll be slow for sure. The generation will be yet slower. 

It is an undeniably slow process, but it is all Mathematica code so you can adjust it at will, which is nice.

Feel free to modify it and optimize. There are certainly many places where it could be much, much better; I mostly developed it to satisfy my personal needs.

If you have any specific requests, let me know and I'll try to get to them in my free time.

**Comment by b3m2a1** [comment]
@GalAster as for the links being broken, the documentation can *only* link correctly when in a paclet directory on the appropriate path. The documentation it generates automatically adds the correct path. You can copy this into your own paclet then select the `"PacletInfo"` option from the `"Regenerate File"` drop-down menu under the `"Dist"` tab. That will automatically relink your docs to your actual app and from then on you can use them.

**Comment by GalAster** [comment]
Well, works fine.

But the templates sometimes crash my frontend.

So if `DocGen` can generate the templates which `Workbench` used that'll be a good backup plan.

**Comment by b3m2a1** [comment]
@GalAster it's certainly on my todo list, but I can't say it's a terribly high priority. I don't use Workbench so I'll have to deconstruct the templates and write code to build them, too. It's a lot of effort and will have to wait until I get back into the swing of documentation writing.

**Comment by GalAster** [comment]
Solved
