### ISSUE TITLE
Import problem with Apps created by BTools 2.0

### ISSUE THREAD

**Issue by GalAster** [b3m2a1/mathematica-BTools#3]
Now I'm working on  a project created by BTools 2.0.

There're still some small problems. 

![image](https://user-images.githubusercontent.com/17541209/37470900-871fd1e0-28a3-11e8-9506-111688cc9465.png)

Here's the broken version, it can be reproduced on today's ver `BTools 2.0.18`

https://github.com/wjxway/ZhihuLink-Mathematica/releases/download/v0.1.13/ZhihuLink-0.1.13.paclet

I use the old `Loader.m` created by BTools 1.0 and then it works.

https://github.com/wjxway/ZhihuLink-Mathematica/commit/3502f8c2979a5694586ff7d8a4bf4f3d5bfbe99c#diff-48f59ab175e2bd47a999a3bce0fcd970

**Comment by b3m2a1** [comment]
I'll take a look at this. I think it's a bug in how I try to load custom preferences.

**Comment by b3m2a1** [comment]
@GalAster so it looks like I patched a version of that bug semi-recently. Does it still happen after you regenerate the load script via:

```mathematica
<<BTools`Paclets`;
AppConfigRegenerate["ObjectFramework", "Loader"]
```

**Comment by b3m2a1** [comment]
Sorry that should have been
`"ZhihuLink"` not `"ObjectFramework"`

**Comment by GalAster** [comment]
Right, this works.

---

Something interesting:

![image](https://user-images.githubusercontent.com/17541209/37500539-f861b772-2904-11e8-8e3f-59df73ad57b7.png)

And `Import` BTools subapps change the `Context[]`, is this normal?
