### ISSUE TITLE
GitHub thinks every method needs authorization

### ISSUE THREAD

**Issue by kubaPod** [b3m2a1/mathematica-BTools#8]
<< BTools`External`
    GitHub["ListRepositories", "b3m2a1"]

It will ask you to login, you can login provide wrong credentials or cancel and it will return ListRepositories result anyway. It should not ask I guess.

**Comment by b3m2a1** [comment]
@kubaPod this is actually a design decision that I feel iffy about. I must have asked for the `$GitHubUsername` somewhere in the call and that automatically asks the user for both username and password. Now, I partially think this is an oversight as there is no need to ask for that, but I also need to think about whether asking for the password when I get the username is smart or whether I should just ask for that later

**Comment by kubaPod** [comment]
What do you need the name for if the author name is provided as an argument? (Makes sense for one argument case but can be missleading as you can ask to listrepositories of someone else) Or am I missing the point?

**Comment by b3m2a1** [comment]
It turned out I was requesting it for every query as an optimization and I just didn’t notice it because I use the request with my keychain so I never actually authenticate. I fixed that up and it ought to work with the most recent paclet on my server.

**Comment by kubaPod** [comment]
Works! Thanks.
